# Generated by Django 3.2.18 on 2023-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='fb4d1d5fb94e4559b5dad805e70f2ade', unique=True, verbose_name='Nombre unico de stock'),
        ),
    ]
