# Generated by Django 3.2.18 on 2023-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='5c9875dfb52e4c8fb78b7a7fdc4fb55e', unique=True, verbose_name='Nombre unico de producto'),
        ),
    ]
