# Generated by Django 3.2.18 on 2023-05-01 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spacelimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(102400)])),
            ],
        ),
    ]
