# Generated by Django 3.2.18 on 2023-04-29 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_spacelimiter_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacelimiter',
            name='size',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(102400)]),
        ),
    ]
